name: Build and Push Docker Image to GHCR

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight (UTC)
  push:
    tags:
      - 'v*.*.*' 
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 3: Determine Image Tag
      - name: Determine Image Tag
        id: vars
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
            echo "TAG=$VERSION" >> $GITHUB_ENV
          else
            echo "TAG=weekly-$(date +%Y-%m-%d)" >> $GITHUB_ENV
          fi

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ipmonitor:${TAG} .
          docker tag ghcr.io/${{ github.repository_owner }}/ipmonitor:${TAG} ghcr.io/${{ github.repository_owner }}/ipmonitor:latest

      # Step 5: Push Docker Images
      - name: Push Docker Images to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ipmonitor:${TAG}
          docker push ghcr.io/${{ github.repository_owner }}/ipmonitor:latest

      # Step 6: Cleanup Docker Local Environment
      - name: Cleanup Docker Local Environment
        run: docker system prune -af
